### ISSUE TITLE
Missing: Tezos Fellowship 

### ISSUE THREAD

**Issue by RavirajWadnerkar** [AkashM398/DSCOMG-OS-101#1]
Can I add Tezos fellowship on the list? 
As it has a Summer of Code style environment and an Open Source Program powered by Devfolio.

Here's a link to the website: [Tezos](https://tezos.com/)
Here's a link to their blog page: [Tezos India](https://medium.com/tezos-india-foundation/presenting-the-tezos-india-fellowship-%EF%B8%8F-1ad13f90b13d)

**Comment by AkashM398** [comment]
Sure @RavirajWadnerkar go ahead and add it
